# Generated by Django 5.1.4 on 2025-01-31 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_champu_product_champu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='champu',
        ),
        migrations.DeleteModel(
            name='Champu',
        ),
    ]
