# Generated by Django 5.1.4 on 2025-01-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_color_variant_product_color_variants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color_variants',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_variants',
            new_name='size_variant',
        ),
    ]
