# Generated by Django 5.1.4 on 2025-02-07 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_color_variants_product_color_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.IntegerField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
                ('minimum_amount', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
                'ordering': ['valid_from'],
            },
        ),
    ]
